name: kalas1
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cloud_firestore: any

  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  carousel_pro: ^1.0.0
  auto_size_text: ^2.1.0
  firebase_auth: ^0.16.0
  shared_preferences: ^0.5.6+3
  firebase_storage: ^3.1.5
  firebase_database: ^3.1.3
  image_picker: ^0.6.5
  firebase_core: ^0.4.4+3


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - agri/s1.jpg
    - agri/s2.jpg
    - agri/s3.png
    - agri/s4.jpg
    - agri/farmtool.jpg
    - agri/organic1.jpg
    - agri/tool3.png
    - agri/pest.jpg
    - agri/plantsed.jpg
    - agri/t1.jpg
    - agri/t2.jpg
    - agri/p1.jpg
    - agri/t4.jpg
    - agri/t5.jpg
    - agri/p2.png
    - agri/fb.png
    - agri/gg.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
